name: dartbase_admin
description: A dart-native implementation of the Firebase Admin SDK to enable administrive tasks to your firebase project.
version: 0.1.4
homepage: https://github.com/SwissCheese5/Dartbase-Admin-SDK
repository: https://github.com/SwissCheese5/Dartbase-Admin-SDK

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  googleapis_auth: ^1.1.0
  eosdart_ecc: ^0.4.3
  gcloud: ^0.7.3
  json_annotation: ^4.0.1
  meta: ^1.3.0
  corsac_jwt: ^0.4.0

dependency_overrides:
  http: ^0.13.1
  crypto: ^3.0.1
  protobuf: ^2.0.0
  grpc: ^3.0.0
  crypto_keys: ^0.3.0
  pointycastle: ^3.0.1
  logging: ^1.0.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8
  pedantic: ^1.11.0
  firedart: ^0.9.0+1
