name: dartbase_admin
description: A dart-native implementation of the Firebase Admin SDK to enable administrive tasks to your firebase project.
version: 0.1.4
homepage: https://github.com/SwissCheese5/Dartbase-Admin-SDK
repository: https://github.com/SwissCheese5/Dartbase-Admin-SDK

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.2
  grpc: ^2.1.3
  protobuf: ^1.0.1
  googleapis_auth: ^0.2.11
  gcloud: ^0.7.0+1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  corsac_jwt: ^0.2.2
  eosdart_ecc: ^0.4.3

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.14.3
  pedantic: ^1.9.0
  firedart: ^0.8.0+1
